# Generated by Django 5.2 on 2025-05-14 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_operation_account_alter_operation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
