# Generated by Django 5.2 on 2025-05-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_operation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Дохід'), ('EXPENSE', 'Витрата')], default='INCOME', max_length=10),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Дохід'), ('EXPENSE', 'Витрата')], default='INCOME', max_length=10),
        ),
        migrations.AlterField(
            model_name='recurring',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Дохід'), ('EXPENSE', 'Витрата')], default='INCOME', max_length=10),
        ),
    ]
