# Generated by Django 5.2 on 2025-05-23 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_budget_category_alter_budget_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='tags',
        ),
        migrations.AddField(
            model_name='operation',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='core.tag'),
        ),
    ]
