# Generated by Django 5.2 on 2025-05-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_operation_tags_operation_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Дохід'), ('EXPENSE', 'Витрата')], default='EXPENSE', max_length=10),
        ),
    ]
