# Generated by Django 5.2 on 2025-05-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Дохід'), ('EXPENSE', 'Витрата')], default='EXPENSE', max_length=10),
        ),
    ]
