# Generated by Django 5.2 on 2025-05-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('UAH', '₴ Гривня'), ('USD', '$ Долар'), ('EUR', '€ Євро')], default='UAH', max_length=3),
        ),
    ]
