# Generated by Django 5.2 on 2025-05-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Категорія, до якої належить цей тег', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.category'),
        ),
    ]
