# Generated by Django 5.2 on 2025-05-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Повторювана операція'),
        ),
        migrations.AddField(
            model_name='operation',
            name='recurring_frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'Щодня'), ('WEEKLY', 'Щотижня'), ('MONTHLY', 'Щомісяця'), ('YEARLY', 'Щороку')], max_length=20, null=True, verbose_name='Частота повторення'),
        ),
        migrations.AlterField(
            model_name='recurring',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Щодня'), ('WEEKLY', 'Щотижня'), ('MONTHLY', 'Щомісяця'), ('YEARLY', 'Щороку')], default='MONTHLY', max_length=10),
        ),
    ]
