# Generated by Django 5.2 on 2025-05-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_operation_is_recurring_operation_recurring_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='recurring_frequency',
        ),
    ]
