# Generated by Django 5.2 on 2025-06-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('user', 'USER'), ('guest', 'GUEST')], default='user', max_length=20),
        ),
    ]
